### ISSUE TITLE
Make position editable

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-free-shipping-progress-bar-block#8] opened 2021-09-23 03:40 UTC
By default, the free shipping progress bar will be displayed above the cart totals of the cart block. To allow merchants to move the progress bar to a different section, the position should be editable.

**Comment by senadir** [comment] 2021-09-24 08:14
As a block, you get the possibility to move anywhere defined on Cart and Checkout, so this is not something you should be solving as it's already solved for you.

**Comment by nielslange** [comment] 2021-09-24 08:39
I was thinking about adjusting the position if this block gets integrated into another block, similar to the atomic blocks that form the cart and checkout blocks. At the moment, these atomic blocks have a fixed position which cannot be adjusted.

![atomic-blocks-in-cart-i2](https://user-images.githubusercontent.com/3323310/134644445-4a7476b0-eece-419f-8685-3eda79a0ec1c.png)

Using this block as a standalone block above the cart block or the add-ons block later, might lead to confusion if the free shipping progress bar is not positioned closely to the shipping options. 

Do you think it's worth to move this issue into the icebox for now, or would you rather suggest closing it, @senadir?

**Comment by senadir** [comment] 2021-09-24 08:48
> At the moment, these atomic blocks have a fixed position which cannot be adjusted.

This is by design, I actually spent a lot of time (https://github.com/WordPress/gutenberg/pull/32457, https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4454) to make that happen. By default, your block would be moveable inside cart and checkout.

If you insert Terms and Conditions block in Checkout, you can see how it can move around the block.
So there's nothing to solve here, you can close it.

**Comment by nielslange** [comment] 2021-09-24 10:07
Happy to close this issue, but can you tell me how to add the T&C block into the Checkout block? Somehow, I'm not able to achieve this on my end:

<table>
<tr>
<td valign="top">

<img width="338" alt="Screenshot 2021-09-24 at 17 01 37" src="https://user-images.githubusercontent.com/3323310/134656929-47d8c29b-0c5a-44ca-b4d6-37ebdbc97dd7.png">
</td>
<td valign="top">

<img width="1027" alt="Screenshot 2021-09-24 at 17 06 37" src="https://user-images.githubusercontent.com/3323310/134657594-5855537a-726a-4811-b1cc-9e36a0c113b2.png">
</td>
</tr>
</table>

**Closed as completed** 2021-10-11 00:11 UTC
Labels: type: enhancement
